from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
ASSETS_DIR = ROOT_DIR / "assets"

# Window
WINDOW_CAPTION = "KobeIceTea"
FPS = 60

# Board
GRID_SIZE = 9
CELL_SIZE = 72
BOARD_PADDING = 24
HUD_HEIGHT = 210

# Gameplay
REWARD_SPAWN_INTERVAL = 3

# Assets
PLAYER_ASSET_NAME = "Kobe.png"
REWARD_ASSET_NAME = "reward.png"
PLAYER_SPRITE_SCALE = 0.72
REWARD_SPRITE_SCALE = 0.72

# Colors
BACKGROUND_COLOR = (244, 239, 224)
PANEL_COLOR = (252, 248, 240)
BORDER_COLOR = (128, 109, 92)
CELL_LIGHT_COLOR = (234, 223, 204)
CELL_DARK_COLOR = (222, 208, 186)
TEXT_COLOR = (58, 47, 35)
ACCENT_COLOR = (176, 93, 49)

# Reinforcement Learning
AUTO_TRAIN_RL = True
GUIDE_MODE_DEFAULT = True
AUTOPLAY_DEFAULT = False
AUTOPLAY_DELAY_MS = 220

RL_RANDOM_SEED = 7
RL_EPISODES = 3000
RL_MAX_ACTIONS_PER_EPISODE = 90
RL_EVALUATION_EPISODES = 200

RL_LEARNING_RATE = 0.18
RL_DISCOUNT_FACTOR = 0.95
RL_EPSILON_START = 1.0
RL_EPSILON_MIN = 0.05
RL_EPSILON_DECAY = 0.997

# The state keeps only a bucketed reward count instead of the full reward map.
RL_REWARD_COUNT_BUCKET_CAP = 3

# Reward shaping
RL_STEP_PENALTY = -0.04
RL_INVALID_MOVE_PENALTY = -1.5
RL_COLLECT_REWARD_BONUS = 10.0
RL_MOVE_CLOSER_BONUS = 0.25
RL_MOVE_AWAY_PENALTY = -0.25
